# Generated by Django 6.0.4 on 2026-04-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bebida', 'Bebida'), ('comida', 'Comida'), ('te', 'Té')], max_length=50),
        ),
    ]
