# Generated by Django 6.0.4 on 2026-04-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
