# Generated by Django 6.0.4 on 2026-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_etiqueta_remove_producto_etiquetas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('horario_lunes_viernes', models.CharField(max_length=100)),
                ('horario_sabado', models.CharField(max_length=100)),
                ('horario_domingo', models.CharField(max_length=100)),
            ],
        ),
    ]
