# Generated by Django 6.0.4 on 2026-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('tiktok', models.URLField()),
                ('mensaje_reserva', models.CharField(default='Hola, quiero hacer una reserva', max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
