# Generated by Django 6.0.4 on 2026-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Quiénes Somos', max_length=150)),
                ('descripcion_1', models.TextField()),
                ('descripcion_2', models.TextField()),
                ('descripcion_3', models.TextField(blank=True, null=True)),
                ('frase_destacada', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='inicio/quienes_somos/')),
            ],
            options={
                'verbose_name': 'Quiénes Somos',
                'verbose_name_plural': 'Quiénes Somos',
            },
        ),
    ]
