# Generated by Django 6.0.4 on 2026-04-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diferencial_quienessomos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quienessomos',
            options={},
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='descripcion_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='frase_destacada',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/quienes_somos/'),
        ),
    ]
