# Generated by Django 6.0.4 on 2026-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_quienessomos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=250)),
                ('respuesta', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
