# Generated by Django 6.0.4 on 2026-04-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_preguntafrecuente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntafrecuente',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='pregunta',
            field=models.CharField(max_length=300),
        ),
    ]
